version: '3.8'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      # copy the sql script to create tables
      - ./dev/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to seed tables
      - ./dev/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

