--  create trainers db
CREATE TABLE trainers (
  trainer_id integer PRIMARY KEY,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL
);

-- create customers db
CREATE TABLE customers (
   customer_id integer PRIMARY KEY,
   first_name varchar(50) NOT NULL,
   last_name varchar(50) NOT NULL
);

-- create appointments table
CREATE TABLE appointments (
  appointment_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  starts_at timestamp WITH time zone NOT NULL,
  ends_at timestamp WITH time zone NOT NULL,
  name varchar(200),
  trainer_id integer,
  FOREIGN KEY (trainer_id) REFERENCES trainers(trainer_id),
  customer_id integer DEFAULT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);